spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AixsCode/config-repo
          user: 15858196281@163.com
          password: 5035811wang
eureka:
  client:
    service-url:
    defaultZone: http://localhost:8761/eureka/
